---
# Bastion host to remote servers
# Default SSH user Ansible will use to connect to hosts
#ansible_user: ubuntu

# Paths to key
#ssh_key_paths:
#  bastion: ~/.ssh/mye-bastion-key
#  nginx: ~/.ssh/mye-bastion-key
#  webapp: ~/.ssh/mye-bastion-key
#  db: ~/.ssh/mye-bastion-key

# Default Bastion
#bastion_host: bastion

#ansible_ssh_common_args: >-
#  -o ProxyCommand="ssh -i {{ bastion_key_path }} -W %h:%p {{ ansible_user }}@{{ hostvars['bastion'].ansible_host }}"

#---------------------------------------------------

# Internal Ports (inside containers/instance)
webapp_port: 5000
db_port: 5432

# Container Images
app_image: "python:3.11-slim"
postgres_image: "postgres:15"

# Host to container port mappings (exposed to outside world)
app_host_ports: 5000
db_host_port: 5432

# Firewall (UFW) rules
ufw_allow_ssh_from: "10.0.0.0/8"
#ufw_allow_ssh_from: "{{ hostvars['bastion']['ansible_host'] }}"

