---
- name: Baseline and platform hardening
  hosts: all
  become: true
  roles:
    - system_hardening
    - ssh_hardening
    - container_platform

- name: Deploy application containers (webapp group)
  hosts: webapp
  become: true
  roles:
    - app_service

- name: Deploy database container (db group)
  hosts: db
  become: true
  roles:
    - postgres_service

- name: Configure Nginx
  hosts: nginx
  become: true
  roles:
    - nginx
